<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateHouseavailabilityTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('houseavailability', function (Blueprint $table) {
            $table->integer('numberID');
            $table->tinyInteger('rentShared');
            $table->tinyInteger('availability')->nullable();
            $table->date('nextAvailableDate')->nullable();
            $table->integer('minStayTerm')->nullable();
            $table->string('minStayUnit', 5)->nullable();
            $table->tinyInteger('allowCooking')->nullable();
            $table->tinyInteger('furnished')->nullable();
            $table->string('availabilityNote', 300)->nullable();

            $table->primary('numberID');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('houseavailability');
    }
}
