<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateInvoicehouseTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('invoicehouse', function (Blueprint $table) {
            $table->integer('invoiceNumber')->nullable();
            $table->integer('houseID')->nullable();
            $table->string('bookingComfirmNumber', 20)->nullable();
            $table->date('rentalDateFrom')->nullable();
            $table->date('rentalDateTo')->nullable();
            $table->integer('salesUnit')->nullable();
            $table->integer('salesPerUnit')->nullable();
            $table->integer('salesCleaningFee')->nullable();
            $table->integer('airbnbFee')->nullable();
            $table->integer('airbnbServiceFee')->nullable();
            $table->integer('securityDeposit')->nullable();
            $table->integer('agentCommission')->nullable();
            $table->string('agentPaidOutCheckNum', 20)->nullable();
            $table->integer('salesTotal')->nullable();
            $table->string('transactionStatementNumber', 20)->nullable();
            $table->date('revenuePaidOutDate')->nullable();
            $table->string('paidOutCheckNum', 20)->nullable();
            $table->string('payableTo', 20)->nullable();
            $table->string('rentalDescription', 250)->nullable();
            $table->integer('costPerUnit')->nullable();
            $table->integer('costCleaningFee')->nullable();
            $table->integer('miscFee')->nullable();
            $table->integer('costTotal')->nullable();
            $table->integer('profitTotal')->nullable();

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('invoicehouse');
    }
}
