<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateInvoiceserviceTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('invoiceservice', function (Blueprint $table) {
            $table->integer('serviceID')->nullable();
            $table->integer('invoiceNumber')->nullable();
            $table->integer('vendorID')->nullable();
            $table->string('serviceDescription', 250)->nullable();
            $table->integer('salesUnit')->nullable();
            $table->integer('salesPerUnit')->nullable();
            $table->integer('serviceFee')->nullable();
            $table->integer('salesTotal')->nullable();
            $table->string('vecdorInvoiceNumber', 20)->nullable();
            $table->string('paidOutCheckNum', 20)->nullable();
            $table->string('payableTo', 40)->nullable();
            $table->integer('costPerUnit')->nullable();
            $table->integer('costTotal')->nullable();
            $table->integer('profitTotal')->nullable();

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('invoiceservice');
    }
}
