<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateHousepriceTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('houseprice', function (Blueprint $table) {
            $table->integer('numberID');
            $table->integer('costDayPrice')->nullable();
            $table->integer('costWeekPrice')->nullable();
            $table->integer('costMonthPrice')->nullable();
            $table->integer('costUtility')->nullable();
            $table->integer('costCleaning')->nullable();
            $table->integer('costSecurityDeposit')->nullable();
            $table->integer('retailDayPrice')->nullable();
            $table->integer('retailWeekPrice')->nullable();
            $table->integer('retailMonthPrice')->nullable();
            $table->string('retailUtility', 50)->nullable();
            $table->integer('retailCleaning')->nullable();
            $table->integer('retailSecurityDeposit')->nullable();
            $table->double('upsellPercent')->nullable();
            $table->double('totPercent')->nullable();
            $table->string('utilityNote', 300)->nullable();
            $table->string('costNote', 300)->nullable();

            $table->primary('numberID');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('houseprice');
    }
}
