<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateHouseroomTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('houseroom', function (Blueprint $table) {
            $table->integer('numberID');
            $table->integer('roomID');
            $table->string('roomType', 20)->nullable();
            $table->string('roomTypeOther', 20)->nullable();
            $table->string('roomBedType', 20)->nullable();
            $table->string('roomBedTypeOther', 20)->nullable();
            $table->char('roomGuestMax', 11)->nullable();
            $table->integer('roomCostDayPrice')->nullable();
            $table->integer('roomCostWeekPrice')->nullable();
            $table->integer('roomCostMonthPrice')->nullable();
            $table->integer('roomCostUtility')->nullable();
            $table->string('utilityNote', 400)->nullable();
            $table->integer('roomCostCleaning')->nullable();
            $table->integer('roomCostSecurityDeposit')->nullable();
            $table->integer('roomRetailDayPrice')->nullable();
            $table->integer('roomRetailWeekPrice')->nullable();
            $table->integer('roomRetailMonthPrice')->nullable();
            $table->integer('roomRetailUtility')->nullable();
            $table->integer('roomRetailCleaning')->nullable();
            $table->integer('roomRetailSecurityDeposit')->nullable();

            $table->primary(['numberID', 'roomID']);

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('houseroom');
    }
}
