<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateRepresentativesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('representatives', function (Blueprint $table) {
            $table->increments('repID')->comment('representative ID');
            $table->tinyInteger('active')->nullable();
            $table->string('repUserName', 20)->nullable();
            $table->string('repPassword', 60)->nullable();
            $table->string('repName', 40)->nullable();
            $table->integer('repPriority')->nullable();
            $table->string('repPosition', 40)->nullable();
            $table->integer('employeeID')->nullable();
            $table->string('employeeFirstName', 20)->nullable();
            $table->string('employeeLastName', 20)->nullable();

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('representatives');
    }
}
