<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateVendorTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('vendor', function (Blueprint $table) {
            $table->increments('vendorID');
            $table->string('vendorCompanyName', 40)->nullable();
            $table->string('vendorContactName', 40)->nullable();
            $table->string('vendorPayableName', 40)->nullable();
            $table->string('vendorBankName', 20)->nullable();
            $table->string('vendorBankAccountName', 40)->nullable();
            $table->string('vendorBankAccountRoutingNumber', 10)->nullable();
            $table->string('vendorBankAccountNumber', 20)->nullable();

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('vendor');
    }
}
