<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateHouseownerTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('houseowner', function (Blueprint $table) {
            $table->increments('houseOwnerID');
            $table->string('first', 20)->nullable();
            $table->string('last', 20);
            $table->string('ownerCompanyName', 40)->nullable();
            $table->string('ownerUsPhoneNumber', 30)->nullable();
            $table->string('ownerPhone2Country', 43)->nullable();
            $table->string('ownerPhone2Number', 30)->nullable();
            $table->string('ownerEmail', 40)->nullable();
            $table->string('ownerWechatUserName', 20)->nullable();
            $table->string('ownerWechatID', 20)->nullable();
            $table->string('ownerOtherID', 20)->nullable();
            $table->string('bankAccountName', 250)->nullable();
            $table->string('bankName', 40)->nullable();
            $table->string('bankRountingNumber', 25)->nullable();
            $table->string('bankAccountNumber', 25)->nullable();

            $table->unique('houseOwnerID', 'houseOwnerID');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('houseowner');
    }
}
