<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCustomerTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('customer', function (Blueprint $table) {
            $table->increments('customerID');
            $table->string('customerCompanyName', 40)->nullable();
            $table->string('customerContactName', 20)->nullable();
            $table->string('customerFirst', 20)->nullable();
            $table->string('customerLast', 20)->nullable();
            $table->string('customerForeignCountry', 40)->nullable();
            $table->string('customerForeignProvince', 30)->nullable();
            $table->string('customerForeignAdd', 40)->nullable();
            $table->string('customerUSAdd', 40)->nullable();
            $table->string('customerUSCity', 20)->nullable();
            $table->string('customerUSState', 20)->nullable();
            $table->string('customerUSZip', 10)->nullable();
            $table->string('customerPhoneCountry', 5)->nullable();
            $table->string('customerPhoneNumber', 15)->nullable();
            $table->string('customerEmail', 40)->nullable();
            $table->string('customerWechatName', 20)->nullable();
            $table->string('customerWechatID', 20)->nullable();
            $table->string('customerWebsite', 100)->nullable();
            $table->string('customerCreditCardNum', 16)->nullable();
            $table->integer('customerCreditCardExpMon')->nullable();
            $table->integer('customerCreditCardExpYear')->nullable();
            $table->integer('customerCredirCardCVV')->nullable();
            $table->string('customerNameOnCreditCard', 40)->nullable();
            $table->string('customerCreditCardType', 20)->nullable();

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('customer');
    }
}
